kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: java:11
  SourceLocation: .
  SourceType: local
  Ports:
  - 8778/TCP
  - 8080/TCP
  - 8443/TCP
  Application: app
  Project: jbsandbox
  Name: refarch-kc-vessel-simulator
